name: Project Management

on:
  pull_request_target:
    branches: [development]
    types: [opened]

jobs:
  labeling:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Labeling
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

