name: Workflow Run Testing

on:
  workflow_run:
    workflows: ["Project Management"]
    branches: [development]
    types: [completed]

jobs:
  workflow-run:
    runs-on: ubuntu-latest
    steps:
      - name: Say something
        run: echo 'Yey, It's work!'
